#ifndef LIBXSMM_VERSION_H
#define LIBXSMM_VERSION_H

#define LIBXSMM_CONFIG_VERSION "1.17-2251"
#define LIBXSMM_CONFIG_BRANCH "master"
#define LIBXSMM_CONFIG_VERSION_MAJOR 1
#define LIBXSMM_CONFIG_VERSION_MINOR 17
#define LIBXSMM_CONFIG_VERSION_UPDATE 0
#define LIBXSMM_CONFIG_VERSION_PATCH 2251
#define LIBXSMM_CONFIG_BUILD_DATE 20220512

#endif

